//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCalcuTeApuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int IdComentario { get; set; }
        public string CodUsuario { get; set; }
        public string DesComentario { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
