//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuCalcuTeApuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramasDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramasDetalle()
        {
            this.UsuariosJugadas = new HashSet<UsuariosJugadas>();
        }
    
        public int CodProgramaDetalle { get; set; }
        public Nullable<int> CodPrograma { get; set; }
        public string DesPrograma { get; set; }
        public string NombreCortoTorneo { get; set; }
        public string CodigoIntralot { get; set; }
        public string Minimo { get; set; }
        public string DesEquipoLocal { get; set; }
        public string DesEquipoVisita { get; set; }
        public string L { get; set; }
        public string E { get; set; }
        public string V { get; set; }
        public string LoE { get; set; }
        public string LoV { get; set; }
        public string EoV { get; set; }
        public string PTL { get; set; }
        public string PTE { get; set; }
        public string PTV { get; set; }
        public string STL { get; set; }
        public string STE { get; set; }
        public string STV { get; set; }
        public string LL { get; set; }
        public string EL { get; set; }
        public string VL { get; set; }
        public string LE { get; set; }
        public string EE { get; set; }
        public string VE { get; set; }
        public string LV { get; set; }
        public string EV { get; set; }
        public string VV { get; set; }
        public string MENOSUNOCINCO { get; set; }
        public string MASUNOCINCO { get; set; }
        public string MENOSDOSCINCO { get; set; }
        public string MASDOSCINCO { get; set; }
        public string MENOSTRESCINCO { get; set; }
        public string MASTRESCINCO { get; set; }
        public string CEROUNO { get; set; }
        public string DOSTRES { get; set; }
        public string CUATROMAS { get; set; }
        public string AMBOS { get; set; }
        public string NINGUNO { get; set; }
        public string IMPAR { get; set; }
        public string PAR { get; set; }
    
        public virtual Programas Programas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosJugadas> UsuariosJugadas { get; set; }
    }
}
